/*
 * Copyright (c) 2003, 2007-14 Matteo Frigo
 * Copyright (c) 2003, 2007-14 Massachusetts Institute of Technology
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/* This file was automatically generated --- DO NOT EDIT */
/* Generated on Sat Jul 30 16:36:05 EDT 2016 */

#include "codelet-dft.h"

#ifdef HAVE_FMA

/* Generated by: ../../../genfft/gen_twiddle.native -fma -reorder-insns -schedule-for-pipeline -compact -variables 4 -pipeline-latency 4 -n 2 -name t1_2 -include t.h */

/*
 * This function contains 6 FP additions, 4 FP multiplications,
 * (or, 4 additions, 2 multiplications, 2 fused multiply/add),
 * 11 stack variables, 0 constants, and 8 memory accesses
 */
#include "t.h"

static void t1_2(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
     {
	  INT m;
	  for (m = mb, W = W + (mb * 2); m < me; m = m + 1, ri = ri + ms, ii = ii + ms, W = W + 2, MAKE_VOLATILE_STRIDE(4, rs)) {
	       E T1, Ta, T3, T6, T2, T5;
	       T1 = ri[0];
	       Ta = ii[0];
	       T3 = ri[WS(rs, 1)];
	       T6 = ii[WS(rs, 1)];
	       T2 = W[0];
	       T5 = W[1];
	       {
		    E T8, T4, T9, T7;
		    T8 = T2 * T6;
		    T4 = T2 * T3;
		    T9 = FNMS(T5, T3, T8);
		    T7 = FMA(T5, T6, T4);
		    ii[0] = T9 + Ta;
		    ii[WS(rs, 1)] = Ta - T9;
		    ri[0] = T1 + T7;
		    ri[WS(rs, 1)] = T1 - T7;
	       }
	  }
     }
}

static const tw_instr twinstr[] = {
     {TW_FULL, 0, 2},
     {TW_NEXT, 1, 0}
};

static const ct_desc desc = { 2, "t1_2", twinstr, &GENUS, {4, 2, 2, 0}, 0, 0, 0 };

void X(codelet_t1_2) (planner *p) {
     X(kdft_dit_register) (p, t1_2, &desc);
}
#else				/* HAVE_FMA */

/* Generated by: ../../../genfft/gen_twiddle.native -compact -variables 4 -pipeline-latency 4 -n 2 -name t1_2 -include t.h */

/*
 * This function contains 6 FP additions, 4 FP multiplications,
 * (or, 4 additions, 2 multiplications, 2 fused multiply/add),
 * 9 stack variables, 0 constants, and 8 memory accesses
 */
#include "t.h"
#include <stdio.h>
#include <stdbool.h>
#include <string.h>

extern bool DMR;
extern int ratio;

extern R * outChecksum1;
extern R * outChecksum2;
extern R * dmrInputBuffer;

extern R * dmrOutChecksum1;
extern R * dmrOutChecksum2;

extern R * simpleCoeff;

int count = 0;
static void t1_2(R *ri, R *ii, const R *W, stride rs, INT mb, INT me, INT ms)
{
	// if(me-mb > 64) printf("t1_2 mb me ms: %td %td %td\n", mb, me, ms);
	if(DMR)
     {
     	memcpy(dmrInputBuffer, ri, 4*(me-mb)*sizeof(R));
     	bool recalc = true;

     	while(recalc)
     	{
     		// printf("pos, ri, ii, W: %td %td %td\n", ri, ii, W);
     		// printf("startPos: %td\t outChecksum1: %f\n", startPos, outChecksum1[2*count]);
	     	R sumReal = 0, sumIm = 0;
	     	recalc = false;

		  INT m;
		  for (m = mb, W = W + (mb * 2); m < me; m = m + 1, ri = ri + ms, ii = ii + ms, W = W + 2, MAKE_VOLATILE_STRIDE(4, rs)) {
		       E T1, T8, T6, T7;
		       E dmr, dmr2;
		       T1 = ri[0];
		       T8 = ii[0];
		       sumReal += T1, sumIm += T8;
		       {
			    E T3, T5, T2, T4;
			    T3 = ri[WS(rs, 1)];
			    T5 = ii[WS(rs, 1)];
			    sumReal += T3, sumIm += T5;

			    T2 = W[0];
			    T4 = W[1];
			    T6 = FMA(T2, T3, T4 * T5);
			    dmr = FMA(T2, T3, T4 * T5);
			    if(dmr != T6) 
			    {
			    	printf("t1_2 dmr error in T6! T2: %f\t T3: %f\t T4: %f\t T5:%f\nT6: %f\t dmr: %f\n", T2, T3, T4, T5, T6, dmr);
			    	T6 = FMA(T2, T3, T4 * T5);
			    }

			    T7 = FNMS(T4, T3, T2 * T5);
			    dmr = FNMS(T4, T3, T2 * T5);
			    if(dmr != T7) 
			    {
			    	printf("t1_2 dmr error in T7! T2: %f\t T3: %f\t T4: %f\t T5:%f\nT7: %f\t dmr: %f\n", T2, T3, T4, T5, T7, dmr);
			    	T7 = FNMS(T4, T3, T2 * T5);
			    }	       
			   }
		       // ri[WS(rs, 1)] = T1 - T6;
		       // ii[WS(rs, 1)] = T8 - T7;
		       // ri[0] = T1 + T6;
		       // ii[0] = T7 + T8;
		       dmr = T1 - T6;
		       dmr2 = T1 - T6;
		       ri[WS(rs, 1)] = (dmr==dmr2)? dmr: T1 - T6;

		       dmr = T8 - T7;
		       dmr2 = T8 - T7;
		       ii[WS(rs, 1)] = (dmr==dmr2)? dmr: T8 - T7;

		       dmr = T1 + T6;
		       dmr2 = T1 + T6;
		       ri[0] = (dmr==dmr2)? dmr: T1 + T6;
		       
		       dmr = T7 + T8;
		       dmr2 = T7 + T8;
		       ii[0] = (dmr==dmr2)? dmr: T7 + T8;

		    }

	  	// printf("sum: %f %f\n", sumReal, sumIm);
	  	// printf("checksum: %f %f\n", outChecksum1[2*count], outChecksum1[2*count+1]);
	    // printf("count: %d\n", count);
	    // for(int j=0; j<8192; j++)
	    // {
	    //     if((fabs(sumReal - outChecksum1[2*j]) < 0.0000001) && (fabs(sumIm - outChecksum1[2*j+1])>-0.0000001))
	    //     {
	    //         printf("%d-th sum equal to %d-th checksum\n", count, j);
	    //     }
	    // }
	  // printf("diff %d: %f %f\n", count, fabs(sumReal - outChecksum1[2*count] - outChecksum1[2*count+2]), fabs(sumIm - outChecksum1[2*count+1] - outChecksum1[2*count+3]));
		  R diffReal = sumReal - outChecksum1[2*count] - outChecksum1[2*count+2];
		  R diffIm = sumIm - outChecksum1[2*count+1] - outChecksum1[2*count+3];
	  	  R * pos1;
		  R * pos2;
		  R * cof;
		  // printf("diff %d: %.10f %.10f\n", count, diffReal, diffIm);
		  if(diffReal < -0.0000001 || diffReal > 0.0000001)
		  {
		  	printf("memory error real part\n"); 
		  	//exit(0);
		  	//correct
		  	R cks = - outChecksum2[2*count] - outChecksum2[2*count+2];
		  	pos1 = dmrInputBuffer;
		  	cof = simpleCoeff;
		  	for(int i=0; i<2*(me-mb); i++)
		  	{
		  		// if((count == 10)) printf("temp1, tempc: %f %f\n", pos1[0], cof[0]);
		  		cks += pos1[0] * cof[0];
		  		pos1 += 2, cof ++;
		  	}
	        int index = (int)(diffReal/cks - 0.5);
	        printf("real part error, count %d, index %d: %f %f\n", count, index, diffReal, cks);
	        printf("index %d: %f\n", index, dmrInputBuffer[2*index]);
	        dmrInputBuffer[2*index] -= diffReal;
	        // printf("corrected: %f\n", dmrInputBuffer[2*index]);
	        recalc = true;
	        // exit(0);
		  }
	  	  if(diffIm < -0.0000001 || diffIm > 0.0000001)
		  {
		  	printf("memory error imaginary part\n"); 
		  	//exit(0);
		  	//correct
		  	R cks = - outChecksum2[2*count+1] - outChecksum2[2*count+3];
		  	pos2 = dmrInputBuffer+1;
		  	cof =simpleCoeff;
		  	for(int i=0; i<2*(me-mb); i++)
		  	{
		  		cks += pos2[0] * cof[0];
		  		pos2 += 2, cof ++;
		  	}
	        int index = (int)(diffIm/cks - 0.5);
	        printf("imaginary part error, count %d, index %d: %f %f\n", count, index, diffIm, cks);
	        printf("index %d: %f\n", index, (dmrInputBuffer+1)[2*index]);
	        (dmrInputBuffer+1)[2*index] -= diffIm;
	        recalc = true;
		  }
		  if(recalc)
		  {
			  W = W - 2*me;
			  ri = ri -ms * (me-mb);
			  ii = ii -ms * (me-mb);
			  memcpy(ri, dmrInputBuffer, 4*(me-mb)*sizeof(R));
		  }
	  }
  	  R * pos1;
	  R * pos2;
	  R * cof;
	  pos1 = dmrOutChecksum1;
	  pos2 = dmrOutChecksum2;
	  cof = simpleCoeff;

	  R * posR;
	  R * posI;
	  posR = ri - ms * (me-mb);
	  posI = posR + 1;

	  R temp1, temp2, tempc;
	  for(int j=0; j<2*(me-mb); j++)
	  {	
	  	 temp1 = posR[0], temp2 = posI[0], tempc = cof[0];
	  	 pos1[0] += temp1, pos1[1] += temp2;
	  	 pos2[0] += temp1 * tempc, pos2[1] += temp2 * tempc;
	  	 posR += 2, posI += 2;
	  	 pos1 += 2, pos2 += 2, cof ++;
	  }
	  count += 2;
     }
     else
     {
	  INT m;
	  for (m = mb, W = W + (mb * 2); m < me; m = m + 1, ri = ri + ms, ii = ii + ms, W = W + 2, MAKE_VOLATILE_STRIDE(4, rs)) {
	       E T1, T8, T6, T7;
	       T1 = ri[0];
	       T8 = ii[0];
	       {
		    E T3, T5, T2, T4;
		    T3 = ri[WS(rs, 1)];
		    T5 = ii[WS(rs, 1)];
		    T2 = W[0];
		    T4 = W[1];
		    T6 = FMA(T2, T3, T4 * T5);
		    T7 = FNMS(T4, T3, T2 * T5);
	       }
	       ri[WS(rs, 1)] = T1 - T6;
	       ii[WS(rs, 1)] = T8 - T7;
	       ri[0] = T1 + T6;
	       ii[0] = T7 + T8;
	  }
     }
}

static const tw_instr twinstr[] = {
     {TW_FULL, 0, 2},
     {TW_NEXT, 1, 0}
};

static const ct_desc desc = { 2, "t1_2", twinstr, &GENUS, {4, 2, 2, 0}, 0, 0, 0 };

void X(codelet_t1_2) (planner *p) {
     X(kdft_dit_register) (p, t1_2, &desc);
}
#endif				/* HAVE_FMA */
